# This is a basic workflow to help you get started with Actions

name: System Contract CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "merge_test_script" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
#    runs-on: self-hosted
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies

      - name: Install python dependencies
        run: pip install -r requirements.txt
          
      - name: Install Node Dependencies
        run: |
          npm install
          npm install -g ganache
      
      - name: Run tests
        run: |
          sh generate-test-contracts.sh
          brownie test -v --stateful false
